# Description: This file contains the paths to the output files that are generated by the NEMO1D simulation tool.




paths = {

    "WSQR": {
        "name": "Wave Square",
        "filename": "new_input_deck.nd_wsqr.json"
    },
    "BND": {
        "name": "Bandstructure",
        "filename": "new_input_deck.nd_bnd.json"
    },
    "CHG": {
        "name": "Charge",
        "filename": "new_input_deck.nd_chg.json"
    },
    "CHGTOT": {
        "name": "Total Charge",
        "filename": "new_input_deck.nd_chgtot.json"
    },
    "CURD": {
        "name": "Current Density",
        "filename": "new_input_deck.nd_curd.json"
    },
    "IV": {
        "name": "IV Characteristics",
        "filename": "new_input_deck.nd_iv.json"
    },
    "J_INT_E": {
        "name": "Integrated Current (E)",
        "filename": "new_input_deck.nd_j_int_e.json"
    },
    "J_INT_E_AV": {
        "name": "Average Integrated Current (E)",
        "filename": "new_input_deck.nd_j_int_e_av.json"
    },
    "J_INT_K": {
        "name": "Integrated Current (K)",
        "filename": "new_input_deck.nd_j_int_k.json"
    },
    "J_K": {
        "name": "Current Density vs K",
        "filename": "new_input_deck.nd_j_k.json"
    },
    "J_PHI": {
        "name": "Current vs Potential",
        "filename": "new_input_deck.nd_j_phi.json"
    },
    "KJ_INT_K": {
        "name": "KJ Integrated (K)",
        "filename": "new_input_deck.nd_kj_int_k.json"
    },
    "KJ_K": {
        "name": "KJ vs K",
        "filename": "new_input_deck.nd_kj_k.json"
    },
    "KN_XK_INT_K": {
        "name": "KN XK Integrated (K)",
        "filename": "new_input_deck.nd_kn_xk_int_k.json"
    },
    "N_SHEET": {
        "name": "Sheet Density",
        "filename": "new_input_deck.nd_n_sheet.json"
    },
    "N_XK": {
        "name": "XK Density",
        "filename": "new_input_deck.nd_n_xk.json"
    },
    "N_XK_INT_K": {
        "name": "XK Integrated (K)",
        "filename": "new_input_deck.nd_n_xk_int_k.json"
    },
    "RES": {
        "name": "Resistance",
        "filename": "new_input_deck.nd_res.json"
    },
    "RESENERGY_V": {
        "name": "Resonance Energy vs Voltage",
        "filename": "new_input_deck.nd_ResEnergy_V.json"
    },
    "RESTRANS_E": {
        "name": "Resonance Transmission (E)",
        "filename": "new_input_deck.nd_ResTrans_E.json"
    },
    "RESTRANS_V": {
        "name": "Resonance Transmission (V)",
        "filename": "new_input_deck.nd_ResTrans_V.json"
    },
    "RESWIDTH_V": {
        "name": "Resonance Width vs Voltage",
        "filename": "new_input_deck.nd_ResWidth_V.json"
    },
    "TRAN": {
        "name": "Transmission",
        "filename": "new_input_deck.nd_tran.json"
    },
    "WAVE": {
        "name": "Wavefunction",
        "filename": "new_input_deck.nd_wave.json"
    }
}


inputdeck = '/Users/austintoro/Documents/Coding/NEMO1D-Local_Simtool/simtool/test_AlGaAs_TFn_Cgam.nem'
material_file = '/Users/austintoro/Documents/Coding/NEMO1D-Local_Simtool/simtool/GaAs.mat'

'''' Debuging specific outputs 
band_file =  '/Users/austintoro/Documents/Coding/NEMO1D-Local_Simtool/test_AlGaAs_TFQ_Cgam.nd_bnd.json'
IV_file =  '/Users/austintoro/Documents/Coding/NEMO1D-Local_Simtool/test_AlGaAs_TFQ_Cgam.nd_iv.json'
'''
new_input_deck_filename = 'new_input_deck.nem'

